### ISSUE TITLE
Invalid plugin specification flutter_zalo_login.

### ISSUE THREAD

**Issue by songcamhoi** [duythien0912/flutter_zalo_login#10]
Running "flutter pub get" in flutter_app...                     
Invalid plugin specification flutter_zalo_login.
Invalid "android" plugin specification.

**Comment by andoutica** [comment]
I got same issue when upgrade 0.1.4 version, 
hard code version to 0.1.3 to resolve this case.
flutter_zalo_login: 0.1.3

**Comment by uyit14** [comment]
using "0.1.3", NOT "^0.1.3"

**Comment by duythien0912** [comment]
Hey guys I have been fixing it let using 

```
flutter_zalo_login: ^0.1.8
```

btw I already write docs for setup plugins on Kotlin let check it out

https://github.com/duythien0912/flutter_zalo_login#4-setup-for-android-kotlin

**Comment by duythien0912** [comment]
@andoutica

**Comment by duythien0912** [comment]
Hi guys so I will close it if there is still an error will open again
