### ISSUE TITLE
Lỗi đường dẫn đăng nhập

### ISSUE THREAD

**Issue by zhangask** [duythien0912/flutter_zalo_login#15]
@duythien0912 
Hiện tại khi đăng nhập sẽ xuất hiện popup với đường dẫn https://dev-oauth.zaloapp.com/v3/auth... error 403, làm thế nào để chuyển sang https://oauth.zaloapp.com/v3/auth.... Mong bạn hỗ trợ.

_Originally posted by @zhangask in https://github.com/duythien0912/flutter_zalo_login/issues/8#issuecomment-761612465_

**Comment by duythien0912** [comment]
@zhangask
Bạn check lại cài đặt trong trong trang zalo developer là app đã được kích hoạt + Package name và hash name đúng chưa nhé

![image](https://user-images.githubusercontent.com/20185622/104829948-d6b88180-58ab-11eb-88a3-90fb98329912.png)
![image](https://user-images.githubusercontent.com/20185622/104829984-42025380-58ac-11eb-9d96-9ae0558835e1.png)

**Comment by zhangask** [comment]
Mình đã add Hash key: debug, release, signing và đã kiểm tra Package name hoàn toàn chính xác. Nhưng mà vẫn nhảy sang Url: dev-oauth...

**Comment by duythien0912** [comment]
![image](https://user-images.githubusercontent.com/20185622/104984937-642dda00-5a42-11eb-8782-1fba7875aa4c.png)
@@ kì ta
Nếu chưa được bạn hãy check xem ứng dụng đã kích hoạt chưa nhé

**Comment by zhangask** [comment]
Đã kiểm tra rồi luôn. iOS hoạt động bình thường còn Android thì bị lỗi vậy. Lúc trước còn nhảy qua Webview nhưng giờ mở lên là nhảy sang Browser và với link dev-oauth :(

**Comment by zhangask** [comment]
Đã sửa được! phải hạ phiên bản Zalo SDK xuống v2.5

**Comment by duythien0912** [comment]
@@ oa là do lib android bên zalo update

Nếu được thì bạn giúp mình tạo một pull request được ko 🙌

**Comment by tronghuy5555** [comment]
Bạn ơi bên dev Zalo Android SDK k biết sao mà để Dev Env làm mặc định, có gì bạn update readme `Constant.IS_DEV = false` tại Application nha  🤣  @duythien0912

**Comment by duythien0912** [comment]
Thanks mọi người thì sau khi xem xét thì mình thấy hạ cấp zalo android sdk sẽ ổn hơn và làm cho những project cũ ko bị lỗi như trên

Nên mình đã update thư viện lên `0.1.9+1` và hạ zalosdk từ + (hiện tại là 2.6) xuống còn 2.5.0819

Mình xin đóng issue tại đây nếu còn lỗi mọi người cứ mở lại tự do nhé

**Comment by duythien0912** [comment]
4ab4fef2e76d2e6aa89c1ba2347fde6d8c2ecf30
