### ISSUE TITLE
unstable login process

### ISSUE THREAD

**Issue by maprex** [duythien0912/flutter_zalo_login#19]
We are developing a service. In our service consider zalo social login for vietnamese users.
we use official flutter library of zalo (flutter_zalo_login: ^0.1.9+1) but it is
unstable for us.....we are very confused.

our scenario is this
1'st step : ZaloLoginResult res = await ZaloLogin().logIn();
2'nd step : ZaloProfileModel info = await ZaloLogin().getInfo();
3'rd step : await ZaloLogin().logOut();

this is fine...normally, but some time (try 10 times then 3 or 4 times occurred  ZaloLogin().logIn();  step is not returned...

How can I solve this problem?

**Comment by duythien0912** [comment]
You can use `Completer` and timeout to try catch this. I will close this for now if that happen again I will check it 💪
