### ISSUE TITLE
ARC Semantic Issue (Xcode)

### ISSUE THREAD

**Issue by 91kiennt** [duythien0912/flutter_zalo_login#22]
Hi duythien0912.
Hiện tại sau khi mình add thêm pub flutter_zalo_login version 0.1.10 thì phát sinh ra lỗi như hiện tại. Không rõ là mình có cần update thêm gì không ạ. Mong bạn giúp đỡ!
![Screenshot 2024-03-25 at 14 32 47](https://github.com/duythien0912/flutter_zalo_login/assets/33169797/79b63c51-6040-4bc5-b730-20f5f27d3f6c)

**Comment by haitr** [comment]
Mình bị lỗi y chang. Sửa sao vậy bạn?

**Comment by haitr** [comment]
Mình cũng bị lỗi này, sửa như thế nào vậy bạn?

**Comment by cuongnm01** [comment]
Mình cũng bị lỗi này, mọi người sửa được lỗi này chưa ạ
