### ISSUE TITLE
Không thể đăng nhập trên Android

### ISSUE THREAD

**Issue by zhangask** [duythien0912/flutter_zalo_login#8]
Cám ơn Bạn về Plugin.  Mình đã làm theo hướng dẫn nhưng plugin không hoạt động trên android mong hỗ trợ :(

`E/MethodChannel#flutter_zalo_login(14962): Failed to handle method call
E/MethodChannel#flutter_zalo_login(14962): com.zing.zalo.zalosdk.core.exception.InitializedException: Missing call declare com.zing.zalo.zalosdk.oauth.ZaloSDKApplication in Application or call wrap init
E/MethodChannel#flutter_zalo_login(14962): 	at com.zing.zalo.zalosdk.oauth.ZaloSDK.checkInitialize(Unknown Source:279)
E/MethodChannel#flutter_zalo_login(14962): 	at com.zing.zalo.zalosdk.oauth.ZaloSDK.unauthenticate(Unknown Source:110)
E/MethodChannel#flutter_zalo_login(14962): 	at com.neun.flutter_zalo_login.flutter_zalo_login.FlutterZaloLoginPlugin.onMethodCall(FlutterZaloLoginPlugin.java:92)
E/MethodChannel#flutter_zalo_login(14962): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#flutter_zalo_login(14962): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_zalo_login(14962): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter_zalo_login(14962): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_zalo_login(14962): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_zalo_login(14962): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#flutter_zalo_login(14962): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/MethodChannel#flutter_zalo_login(14962): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_zalo_login(14962): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#flutter_zalo_login(14962): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter (14962): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Missing call declare com.zing.zalo.zalosdk.oauth.ZaloSDKApplication in Application or call wrap init, null)
E/flutter (14962): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
E/flutter (14962): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter (14962): <asynchronous suspension>
E/flutter (14962): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (14962): #3      ZaloLogin.logIn (package:flutter_zalo_login/flutter_zalo_login.dart:15:56)
E/flutter (14962): #4      _LoginScreenState.loginWithZalo (package:myapps/src/pages/login_screen.dart:333:45)
E/flutter (14962): #5      _LoginScreenState.build.<anonymous closure> (package:myapps/src/pages/login_screen.dart:210:35)
E/flutter (14962): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (14962): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (14962): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (14962): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (14962): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (14962): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
E/flutter (14962): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
E/flutter (14962): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
E/flutter (14962): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
E/flutter (14962): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (14962): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
E/flutter (14962): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
E/flutter (14962): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter (14962): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (14962): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (14962): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (14962): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (14962): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (14962): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (14962): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (14962): #26     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter (14962): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)`

**Comment by songcamhoi** [comment]
I am also having the same problem. Do you have a solution yet?

**Comment by vantutrieu97** [comment]
Mình cũng làm theo hướng dẫn mà cũng bị lỗi như trên, có ai biết cách fix chưa ạ

**Comment by duythien0912** [comment]
Hi guys sorry for missed this conversation 

I have been adding an example for Kotlin version and I think it more clear for setup now

I think this issue because step 4.4 you can check it on here

https://github.com/duythien0912/flutter_zalo_login#44-create-either-myapplicationkt-in-the-same-directory-as-mainactivity

**Comment by duythien0912** [comment]
You guys can try with 

```yaml
flutter_zalo_login: ^0.1.8
```

**Comment by duythien0912** [comment]
@zhangask 
@songcamhoi

**Comment by duythien0912** [comment]
Hi guys so I will close it if there is still an error will open again

**Comment by zhangask** [comment]
@duythien0912 
Hiện tại khi đăng nhập sẽ xuất hiện popup với đường dẫn https://dev-oauth.zaloapp.com/v3/auth... error 403, làm thế nào để chuyển sang https://oauth.zaloapp.com/v3/auth.... Mong bạn hỗ trợ.

**Comment by duythien0912** [comment]
@zhangask
Bạn check lại cài đặt trong trong trang zalo developer là app đã được kích hoạt + Package name và hash name đúng chưa nhé

![image](https://user-images.githubusercontent.com/20185622/104829948-d6b88180-58ab-11eb-88a3-90fb98329912.png)
![image](https://user-images.githubusercontent.com/20185622/104829984-42025380-58ac-11eb-9d96-9ae0558835e1.png)
